# Generated by Django 4.2 on 2024-10-23 06:13

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                verbose_name="active",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                verbose_name="archived",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Represents unique uuid.",
                unique=True,
                verbose_name="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created date",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="date updated"),
        ),
    ]
